package se.wintren.map

import android.os.Bundle
import android.support.v7.app.AppCompatActivity
import se.wintren.map_annotation.GenerateClass
import se.wintren.map_annotation.MAP

class MainActivity : AppCompatActivity() {

    @GenerateClass
    class Bubble

    @MAP
    interface DtoMapper {
        fun coolDtoToData(dto: CoolDTO): CoolData
        fun coolDtoToData(skunk: CoolData): CoolDTO
//        fun printMePlease()
    }

    // 1. Annotate interface
    // 2. Annotate abstract class
    // 3. Abstract class with some functions implemented
    // 4. Add a sub dto to CoolDto
    // ( 5. Try to create a non-dependency on generated by overshadowing functions)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        Gen_Bubble("Name").greet()
        // Find out how to debug annotations! :D
    }
}

data class CoolDTO(
    val id: Long,
    val title: String,
    val hasTheCool: Boolean?,
    val coolImageUrl: String?
)

data class CoolData(
    val id: Long,
    val title: String,
    val hasTheCool: Boolean?,
    val coolImageUrl: String?
)

fun doneDtoToData(dto: CoolDTO): CoolData {
    return CoolData(
        id = dto.id,
        title = dto.title,
        hasTheCool = dto.hasTheCool,
        coolImageUrl = dto.coolImageUrl
    )
}